using Mmo.Shared.Entities;
using Mmo.Shared.Enums;
using Mmo.Shared.Records;

namespace Mmo.Shared.Tests.Entities;

public class MobEntityTests
{
    [Fact]
    public void Constructor_WithAutoGeneratedId_CreatesValidMob()
    {
        var position = new Position(100, 200);
        var mob = new MobEntity("Goblin", position, maxHealth: 150);

        Assert.Equal("Goblin", mob.MobName);
        Assert.Equal(150, mob.MaxHealth);
        Assert.Equal(150, mob.CurrentHealth);
        Assert.Equal(position, mob.Position);
        Assert.NotEqual(Guid.Empty, mob.PersistentId);
        Assert.False(mob.IsTrulyPersistent);
        Assert.Equal(EntityType.Mob, mob.Type);
        Assert.Equal(EntityRole.Hostile, mob.Role);
    }

    [Fact]
    public void Constructor_WithSpecificId_UsesProvidedId()
    {
        var persistentId = Guid.NewGuid();
        var position = new Position(50, 75);
        var mob = new MobEntity(persistentId, "Wolf", position, maxHealth: 100);

        Assert.Equal(persistentId, mob.PersistentId);
        Assert.Equal("Wolf", mob.MobName);
        Assert.Equal(100, mob.MaxHealth);
        Assert.Equal(100, mob.CurrentHealth);
        Assert.Equal(position, mob.Position);
        Assert.False(mob.IsTrulyPersistent);
    }

    [Fact]
    public void IsDead_ReturnsTrueWhenHealthIsZero()
    {
        var mob = new MobEntity("Skeleton", new Position(0, 0), maxHealth: 50);
        mob.CurrentHealth = 0;

        Assert.True(mob.IsDead);
    }

    [Fact]
    public void IsDead_ReturnsTrueWhenHealthIsNegative()
    {
        var mob = new MobEntity("Zombie", new Position(0, 0), maxHealth: 75);
        mob.CurrentHealth = -10;

        Assert.True(mob.IsDead);
    }

    [Fact]
    public void IsDead_ReturnsFalseWhenHealthIsPositive()
    {
        var mob = new MobEntity("Orc", new Position(0, 0), maxHealth: 200);
        mob.CurrentHealth = 1;

        Assert.False(mob.IsDead);
    }

    [Fact]
    public void HealthPercentage_ReturnsCorrectValue()
    {
        var mob = new MobEntity("Spider", new Position(0, 0), maxHealth: 100);
        mob.CurrentHealth = 75;

        Assert.Equal(0.75f, mob.HealthPercentage);
    }

    [Fact]
    public void HealthPercentage_ReturnsZeroWhenMaxHealthIsZero()
    {
        var mob = new MobEntity("Bug", new Position(0, 0), maxHealth: 0);
        mob.CurrentHealth = 0;

        Assert.Equal(0f, mob.HealthPercentage);
    }

    [Fact]
    public void HealthPercentage_ReturnsOneWhenFullHealth()
    {
        var mob = new MobEntity("Dragon", new Position(0, 0), maxHealth: 1000);
        mob.CurrentHealth = 1000;

        Assert.Equal(1f, mob.HealthPercentage);
    }

    [Fact]
    public void HealthPercentage_ReturnsZeroWhenDead()
    {
        var mob = new MobEntity("Rat", new Position(0, 0), maxHealth: 20);
        mob.CurrentHealth = 0;

        Assert.Equal(0f, mob.HealthPercentage);
        Assert.True(mob.IsDead);
    }

    [Fact]
    public void ChangeZone_DoesNotThrowException()
    {
        var mob = new MobEntity("Slime", new Position(0, 0));

        // Should not throw
        mob.ChangeZone(5);
    }

    [Fact]
    public void DefaultConstructor_CreatesEmptyMob()
    {
        // This constructor is used by MessagePack deserialization
        var mob = new MobEntity();

        Assert.NotNull(mob);
        Assert.Equal("", mob.MobName);
        Assert.Equal(100, mob.MaxHealth);
        Assert.Equal(100, mob.CurrentHealth);
    }

    [Fact]
    public void TwoMobs_WithAutoGeneratedIds_HaveDifferentPersistentIds()
    {
        var mob1 = new MobEntity("Goblin", new Position(0, 0));
        var mob2 = new MobEntity("Goblin", new Position(0, 0));

        Assert.NotEqual(mob1.PersistentId, mob2.PersistentId);
    }

    [Fact]
    public void Position_CanBeUpdated()
    {
        var mob = new MobEntity("Knight", new Position(10, 20));
        var newPosition = new Position(30, 40);

        mob.Position = newPosition;

        Assert.Equal(newPosition, mob.Position);
        Assert.Equal(30, mob.Position.X);
        Assert.Equal(40, mob.Position.Y);
    }
}
