using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mmo.Generators;

/// <summary>
/// Source generator for Delta DTOs.
/// Generates delta transfer objects grouped by DirtyFlags for entities marked with [GenerateDirtyTracking].
/// </summary>
[Generator]
public class DeltaDtoGenerator : IIncrementalGenerator
{
    private const string GenerateDirtyTrackingAttributeFullName = "Mmo.Shared.Generators.GenerateDirtyTrackingAttribute";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all types with [GenerateDirtyTracking]
        IncrementalValuesProvider<TypeDeclarationSyntax?> typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => GeneratorHelpers.IsCandidateForGeneration(s),
                static (ctx, _) => GeneratorHelpers.GetSemanticTargetForGeneration(ctx, GenerateDirtyTrackingAttributeFullName))
            .Where(static m => m is not null);

        IncrementalValueProvider<(Compilation Left, ImmutableArray<TypeDeclarationSyntax?> Right)> compilationAndTypes =
            context.CompilationProvider.Combine(typeDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndTypes,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax?> types,
        SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
            return;

        var distinctTypes = types.Where(c => c != null).Distinct().ToList();

        foreach (TypeDeclarationSyntax? typeDeclaration in distinctTypes)
        {
            if (typeDeclaration == null)
                continue;

            SemanticModel semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;

            if (typeSymbol == null)
                continue;

            try
            {
                var config = GeneratorHelpers.ExtractConfiguration(typeSymbol);
                var deltaGroups = GeneratorHelpers.GroupPropertiesByDirtyFlags(typeSymbol);
                
                foreach (var group in deltaGroups)
                {
                    string deltaDto = GenerateDeltaDto(typeSymbol, config, group.Key, group.Value);
                    string deltaName = GeneratorHelpers.GetDeltaDtoName(typeSymbol.Name, group.Key);
                    context.AddSource($"{deltaName}.g.cs", 
                        SourceText.From(deltaDto, Encoding.UTF8));
                }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DELTADTO001",
                        "Delta DTO Generation Error",
                        $"Error generating Delta DTOs for {typeSymbol.Name}: {ex.Message}",
                        "DeltaDtoGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        }
    }

    private static string GenerateDeltaDto(INamedTypeSymbol typeSymbol, GeneratorHelpers.DirtyTrackingConfig config, 
        string groupName, List<GeneratorHelpers.TrackedPropertyInfo> properties)
    {
        var sb = new StringBuilder();
        string namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        string deltaName = GeneratorHelpers.GetDeltaDtoName(typeSymbol.Name, groupName);
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using Mmo.Shared.Generators;");
        sb.AppendLine("using Mmo.Shared.Zones.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}.Dtos;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Delta DTO for {groupName}-related changes in {typeSymbol.Name}.");
        sb.AppendLine($"/// Auto-generated by DeltaDtoGenerator.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine("[MessagePackObject]");
        
        string idType = config.IdPropertyType ?? "System.Guid";
        sb.AppendLine($"public class {deltaName} : IDeltaDto<{idType}>");
        sb.AppendLine("{");
        
        // Add ID property
        int keyIndex = 0;
        if (!string.IsNullOrEmpty(config.IdPropertyName))
        {
            sb.AppendLine($"    [Key({keyIndex})]");
            sb.AppendLine($"    [DeltaId]");
            sb.AppendLine($"    public {idType} {config.IdPropertyName} {{ get; set; }}");
            sb.AppendLine();
            keyIndex++;
        }
        
        // Add tracked properties (nullable for delta pattern)
        foreach (var prop in properties)
        {
            string nullableType = GeneratorHelpers.MakeNullable(prop.Type);
            sb.AppendLine($"    [Key({keyIndex})]");
            sb.AppendLine($"    public {nullableType} {prop.Name} {{ get; set; }}");
            sb.AppendLine();
            keyIndex++;
        }
        
        // Add GetId() method
        if (!string.IsNullOrEmpty(config.IdPropertyName))
        {
            sb.AppendLine($"    public {idType} GetId() => {config.IdPropertyName};");
        }
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}
