using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mmo.Generators;

/// <summary>
/// Source generator for Delta extension methods.
/// Generates ToXXXDelta() extension methods for entities marked with [GenerateDirtyTracking].
/// </summary>
[Generator]
public class DeltaExtensionsGenerator : IIncrementalGenerator
{
    private const string GenerateDirtyTrackingAttributeFullName = "Mmo.Shared.Generators.GenerateDirtyTrackingAttribute";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all types with [GenerateDirtyTracking]
        IncrementalValuesProvider<TypeDeclarationSyntax?> typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => GeneratorHelpers.IsCandidateForGeneration(s),
                static (ctx, _) => GeneratorHelpers.GetSemanticTargetForGeneration(ctx, GenerateDirtyTrackingAttributeFullName))
            .Where(static m => m is not null);

        IncrementalValueProvider<(Compilation Left, ImmutableArray<TypeDeclarationSyntax?> Right)> compilationAndTypes =
            context.CompilationProvider.Combine(typeDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndTypes,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax?> types,
        SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
            return;

        var distinctTypes = types.Where(c => c != null).Distinct().ToList();

        foreach (TypeDeclarationSyntax? typeDeclaration in distinctTypes)
        {
            if (typeDeclaration == null)
                continue;

            SemanticModel semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;

            if (typeSymbol == null)
                continue;

            try
            {
                var config = GeneratorHelpers.ExtractConfiguration(typeSymbol);
                var deltaGroups = GeneratorHelpers.GroupPropertiesByDirtyFlags(typeSymbol);
                
                string extensions = GenerateExtensionMethods(typeSymbol, config, deltaGroups);
                context.AddSource($"{typeSymbol.Name}.DeltaExtensions.g.cs",
                    SourceText.From(extensions, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DELTAEXT001",
                        "Delta Extensions Generation Error",
                        $"Error generating extension methods for {typeSymbol.Name}: {ex.Message}",
                        "DeltaExtensionsGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        }
    }

    private static string GenerateExtensionMethods(INamedTypeSymbol typeSymbol, GeneratorHelpers.DirtyTrackingConfig config,
        Dictionary<string, List<GeneratorHelpers.TrackedPropertyInfo>> deltaGroups)
    {
        var sb = new StringBuilder();
        string namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}.Extensions;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Extension methods for converting {typeSymbol.Name} to Delta DTOs.");
        sb.AppendLine($"/// Auto-generated by DeltaExtensionsGenerator.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {typeSymbol.Name}DeltaExtensions");
        sb.AppendLine("{");
        
        foreach (var group in deltaGroups)
        {
            string deltaName = GeneratorHelpers.GetDeltaDtoName(typeSymbol.Name, group.Key);
            string methodName = $"To{group.Key}Delta";
            
            sb.AppendLine($"    public static {namespaceName}.Dtos.{deltaName} {methodName}(this {typeSymbol.ToDisplayString()} entity)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {namespaceName}.Dtos.{deltaName}");
            sb.AppendLine("        {");
            
            if (!string.IsNullOrEmpty(config.IdPropertyName))
            {
                sb.AppendLine($"            {config.IdPropertyName} = entity.{config.IdPropertyName},");
            }
            
            foreach (var prop in group.Value)
            {
                sb.AppendLine($"            {prop.Name} = entity.{prop.Name},");
            }
            
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}
