using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mmo.Generators;

/// <summary>
/// Source generator for IDirtyTrackable implementation.
/// Generates dirty flag tracking functionality for entities marked with [GenerateDirtyTracking].
/// </summary>
[Generator]
public class DirtyTrackableGenerator : IIncrementalGenerator
{
    private const string GenerateDirtyTrackingAttributeFullName = "Mmo.Shared.Generators.GenerateDirtyTrackingAttribute";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all types with [GenerateDirtyTracking]
        IncrementalValuesProvider<TypeDeclarationSyntax?> typeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => GeneratorHelpers.IsCandidateForGeneration(s),
                static (ctx, _) => GeneratorHelpers.GetSemanticTargetForGeneration(ctx, GenerateDirtyTrackingAttributeFullName))
            .Where(static m => m is not null);

        IncrementalValueProvider<(Compilation Left, ImmutableArray<TypeDeclarationSyntax?> Right)> compilationAndTypes =
            context.CompilationProvider.Combine(typeDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndTypes,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax?> types,
        SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
            return;

        var distinctTypes = types.Where(c => c != null).Distinct().ToList();

        foreach (TypeDeclarationSyntax? typeDeclaration in distinctTypes)
        {
            if (typeDeclaration == null)
                continue;

            SemanticModel semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;

            if (typeSymbol == null)
                continue;

            try
            {
                string trackableImpl = GenerateIDirtyTrackableImplementation(typeSymbol);
                
                // Only add source if implementation was generated (non-empty for classes)
                if (!string.IsNullOrWhiteSpace(trackableImpl))
                {
                    context.AddSource($"{typeSymbol.Name}.DirtyTracking.g.cs", 
                        SourceText.From(trackableImpl, Encoding.UTF8));
                }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DIRTYTRACK001",
                        "Dirty Trackable Generation Error",
                        $"Error generating IDirtyTrackable for {typeSymbol.Name}: {ex.Message}",
                        "DirtyTrackableGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        }
    }

    private static string GenerateIDirtyTrackableImplementation(INamedTypeSymbol typeSymbol)
    {
        var sb = new StringBuilder();
        string namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        
        // Only generate for classes, not interfaces
        if (typeSymbol.TypeKind != TypeKind.Class)
        {
            // For interfaces, return empty string - dirty tracking is added by implementing classes
            return string.Empty;
        }
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"partial class {typeSymbol.Name} : Mmo.Shared.Entities.Interfaces.IDirtyTrackable");
        sb.AppendLine("{");
        sb.AppendLine("    private Mmo.Shared.Entities.Enums.EntityDirtyFlags _dirtyFlags = Mmo.Shared.Entities.Enums.EntityDirtyFlags.None;");
        sb.AppendLine();
        sb.AppendLine("    public Mmo.Shared.Entities.Enums.EntityDirtyFlags DirtyFlags => _dirtyFlags;");
        sb.AppendLine("    public bool IsDirty => _dirtyFlags != Mmo.Shared.Entities.Enums.EntityDirtyFlags.None;");
        sb.AppendLine();
        sb.AppendLine("    public void ClearDirtyFlags() => _dirtyFlags = Mmo.Shared.Entities.Enums.EntityDirtyFlags.None;");
        sb.AppendLine("    public void MarkDirty(Mmo.Shared.Entities.Enums.EntityDirtyFlags flags) => _dirtyFlags |= flags;");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}
