using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mmo.Generators;

[Generator]
public class ListEntryGenerator : IIncrementalGenerator
{
    private const string GenerateListEntryAttributeFullName = "Mmo.Shared.Generators.Attributes.GenerateListEntryAttribute";
    private const string BaseDataAttributeName = "BaseDataAttribute";
    private const string OptionalDataAttributeName = "OptionalDataAttribute";
    private const string IgnoreDataAttributeName = "IgnoreDataAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register for classes/structs with [GenerateListEntry] attribute
        IncrementalValuesProvider<TypeDeclarationSyntax?> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => GeneratorHelpers.IsCandidateForGeneration(s),
                static (ctx, _) => GeneratorHelpers.GetSemanticTargetForGeneration(ctx, GenerateListEntryAttributeFullName))
            .Where(static m => m is not null);

        // Combine with compilation
        IncrementalValueProvider<(Compilation Left, ImmutableArray<TypeDeclarationSyntax?> Right)> compilationAndClasses = 
            context.CompilationProvider.Combine(classDeclarations.Collect());

        // Generate source
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static void Execute(Compilation compilation, 
        ImmutableArray<TypeDeclarationSyntax?> classes, 
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty) return;

        var distinctClasses = classes.Where(c => c != null).Distinct().ToList();

        foreach (var typeDeclaration in distinctClasses)
        {
            if (typeDeclaration is null) continue;
            
            var semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
            if (typeSymbol is null) continue;

            try
            {
                // Get all [GenerateListEntry] attributes
                var listEntryAttributes = typeSymbol.GetAttributes()
                    .Where(a => a.AttributeClass?.ToDisplayString() == GenerateListEntryAttributeFullName)
                    .ToList();

                if (!listEntryAttributes.Any()) continue;

                foreach (var attr in listEntryAttributes)
                {
                    var entryTypeName = attr.ConstructorArguments[0].Value?.ToString();
                    if (string.IsNullOrEmpty(entryTypeName)) continue;

                    var generatedSource = GenerateListEntryClass(typeSymbol, entryTypeName!, attr, compilation);
                    context.AddSource($"{typeSymbol.Name}.{entryTypeName}.g.cs", 
                        SourceText.From(generatedSource, Encoding.UTF8));
                }

                // Generate extension methods
                var extensionSource = GenerateExtensionMethods(typeSymbol, listEntryAttributes, compilation);
                context.AddSource($"{typeSymbol.Name}.ListEntryExtensions.g.cs", 
                    SourceText.From(extensionSource, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                // Report diagnostic on error
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "LSTGEN001",
                        "ListEntry generation error",
                        "Error generating ListEntry for {0}: {1}",
                        "ListEntryGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    typeDeclaration.GetLocation(),
                    typeSymbol.Name,
                    ex.Message));
            }
        }
    }

    private static string GenerateListEntryClass(INamedTypeSymbol sourceType, 
        string entryTypeName,
        AttributeData attribute,
        Compilation compilation)
    {
        var sb = new StringBuilder();
        var sourceNamespace = sourceType.ContainingNamespace.ToDisplayString();
        
        // Check if custom namespace is specified
        var customNamespace = attribute.NamedArguments
            .FirstOrDefault(kvp => kvp.Key == "Namespace")
            .Value.Value?.ToString();
        
        var generatedNamespace = !string.IsNullOrEmpty(customNamespace) 
            ? customNamespace 
            : $"{sourceNamespace}.Generated";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using MessagePack;");
        sb.AppendLine();
        sb.AppendLine($"namespace {generatedNamespace};");
        sb.AppendLine();
        sb.AppendLine("[MessagePackObject]");
        sb.AppendLine($"public partial class {entryTypeName}");
        sb.AppendLine("{");

        int keyIndex = 0;
        foreach (var property in GetPropertiesForEntryType(sourceType, entryTypeName))
        {
            var isOptional = property.IsOptional;
            var type = property.Symbol.Type;
            var typeName = type.ToDisplayString();
            var nullableSuffix = isOptional && !IsNullableType(type) ? "?" : "";
            
            // Add default initialization for non-nullable types to avoid compiler warnings
            var defaultValue = "";
            if (!isOptional)
            {
                // For string types use empty string
                if (type.SpecialType == SpecialType.System_String)
                {
                    defaultValue = " = \"\";";
                }
                // For other non-nullable reference types use default!
                else if (type.IsReferenceType && type.NullableAnnotation != NullableAnnotation.Annotated)
                {
                    defaultValue = " = default!;";
                }
            }
            
            sb.AppendLine($"    [Key({keyIndex})]");
            sb.AppendLine($"    public {typeName}{nullableSuffix} {property.Symbol.Name} {{ get; set; }}{defaultValue}");
            sb.AppendLine();
            keyIndex++;
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateExtensionMethods(INamedTypeSymbol sourceType,
        List<AttributeData> listEntryAttributes,
        Compilation compilation)
    {
        var sb = new StringBuilder();
        var sourceNamespace = sourceType.ContainingNamespace.ToDisplayString();
        
        // Get all unique generated namespaces
        var generatedNamespaces = new HashSet<string>();
        foreach (var attr in listEntryAttributes)
        {
            var customNamespace = attr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == "Namespace")
                .Value.Value?.ToString();
            
            var generatedNamespace = !string.IsNullOrEmpty(customNamespace) 
                ? customNamespace 
                : $"{sourceNamespace}.Generated";
            
            generatedNamespaces.Add(generatedNamespace);
        }

        // Use the first namespace (or default) for the extensions class
        var extensionNamespace = generatedNamespaces.FirstOrDefault() ?? $"{sourceNamespace}.Generated";
        var sourceTypeName = sourceType.Name;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {sourceNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {extensionNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {sourceTypeName}ListEntryExtensions");
        sb.AppendLine("{");

        foreach (var attr in listEntryAttributes)
        {
            var entryTypeName = attr.ConstructorArguments[0].Value?.ToString();
            if (string.IsNullOrEmpty(entryTypeName)) continue;

            sb.AppendLine($"    public static {entryTypeName} To{entryTypeName}(this {sourceTypeName} source)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {entryTypeName}");
            sb.AppendLine("        {");

            var properties = GetPropertiesForEntryType(sourceType, entryTypeName!).ToList();
            for (int i = 0; i < properties.Count; i++)
            {
                var property = properties[i];
                var comma = i < properties.Count - 1 ? "," : "";
                sb.AppendLine($"            {property.Symbol.Name} = source.{property.Symbol.Name}{comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<(IPropertySymbol Symbol, bool IsOptional)> GetPropertiesForEntryType(
        INamedTypeSymbol sourceType, 
        string entryTypeName)
    {
        foreach (var member in sourceType.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.DeclaredAccessibility != Accessibility.Public) continue;
            if (member.IsStatic) continue;

            var attributes = member.GetAttributes();
            
            // Check for [BaseData] - always included, non-nullable
            if (attributes.Any(a => a.AttributeClass?.Name == BaseDataAttributeName))
            {
                yield return (member, false);
                continue;
            }

            // Check for [OptionalData("EntryType1", "EntryType2")]
            var optionalAttr = attributes.FirstOrDefault(a => 
                a.AttributeClass?.Name == OptionalDataAttributeName);
            if (optionalAttr != null)
            {
                var entryTypes = optionalAttr.ConstructorArguments[0].Values
                    .Select(v => v.Value?.ToString())
                    .Where(v => v != null)
                    .ToList();

                if (entryTypes.Contains(entryTypeName))
                {
                    yield return (member, true);
                }
            }
            
            // No attribute or [IgnoreData] = skip
        }
    }

    private static bool IsNullableType(ITypeSymbol type)
    {
        // Check if it's already a nullable reference type or nullable value type
        if (type.NullableAnnotation == NullableAnnotation.Annotated)
            return true;
        
        // Check if it's Nullable<T>
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var originalDefinition = namedType.OriginalDefinition.ToDisplayString();
            if (originalDefinition == "System.Nullable<T>")
                return true;
        }
        
        // Check if it's a reference type
        if (!type.IsValueType)
            return true;
        
        return false;
    }
}
