<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.*"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Character\Messages\"/>
    <Folder Include="Character\Records\"/>
    <Folder Include="Entities\Messages\"/>
    <Folder Include="Groups\"/>
  </ItemGroup>

</Project>
